// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

// Injectors from wire.go:

//go:generate wire
func InitApp() (*FooMessage, error) {
	message := ProvideMessage()
	beer := ProvideBeer()
	fooMessage := &FooMessage{
		Msg: message,
		Ber: beer,
	}
	return fooMessage, nil
}

// wire.go:

type Message string

type Beer string

// 测试构造结构体
type FooMessage struct {
	Msg Message
	Ber Beer
}

func ProvideMessage() Message {
	return "info"
}

func ProvideBeer() Beer {
	return "beer"
}
