// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"go-micro-frame-doc/25-wire/06-wire-cleanup/internal/config"
)

// Injectors from wire.go:

//go:generate wire
func InitApp() (*App, func(), error) {
	configConfig, cleanup, err := config.New()
	if err != nil {
		return nil, nil, err
	}
	app := NewApp(configConfig)
	return app, func() {
		cleanup()
	}, nil
}
